[package]
name = "adachi"
version = "0.1.0"
edition.workspace = true

[dependencies]
sithra-kit.workspace = true
tokio.workspace = true
log.workspace = true
fastrand = "2.3.0"
serde.workspace = true
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "json"
] }
ulid.workspace = true
sha2 = "0.10.9"
chrono = "0.4.41"
simple-ai.workspace = true

[lints]
workspace = true
